export const featuredDetails = [
  {
    createdAt: '01-Jan-2023',
    expiresAt: '01-Feb-2023',
    stripeId: 2322424,
    amount: 3000,
    currentStatus: 'Expired',
  },
  {
    createdAt: '05-Feb-2023',
    expiresAt: '05-Mar-2023',
    stripeId: 8787878,
    amount: 5000,
    currentStatus: 'Active',
  },
  {
    createdAt: '10-Mar-2023',
    expiresAt: '10-Apr-2023',
    stripeId: 1234567,
    amount: 7500,
    currentStatus: 'Pending',
  },
  {
    createdAt: '01-Jan-2023',
    expiresAt: '01-Feb-2023',
    stripeId: 2322424,
    amount: 3000,
    currentStatus: 'Expired',
  },
  {
    createdAt: '10-Feb-2023',
    expiresAt: '15-Mar-2023',
    stripeId: 5656565,
    amount: 4500,
    currentStatus: 'Active',
  },
  {
    createdAt: '05-Apr-2023',
    expiresAt: '05-May-2023',
    stripeId: 9090909,
    amount: 6000,
    currentStatus: 'Pending',
  },
  {
    createdAt: '20-May-2023',
    expiresAt: '20-Jun-2023',
    stripeId: 1231231,
    amount: 2000,
    currentStatus: 'Active',
  },
  {
    createdAt: '15-Jul-2023',
    expiresAt: '15-Aug-2023',
    stripeId: 7777777,
    amount: 8000,
    currentStatus: 'Expired',
  },
  {
    createdAt: '01-Sep-2023',
    expiresAt: '01-Oct-2023',
    stripeId: 4545454,
    amount: 3500,
    currentStatus: 'Active',
  },
  {
    createdAt: '10-Oct-2023',
    expiresAt: '10-Nov-2023',
    stripeId: 2222222,
    amount: 5000,
    currentStatus: 'Pending',
  },
  {
    createdAt: '25-Nov-2023',
    expiresAt: '25-Dec-2023',
    stripeId: 8888888,
    amount: 7000,
    currentStatus: 'Expired',
  },
  {
    createdAt: '02-Jan-2023',
    expiresAt: '02-Feb-2023',
    stripeId: 9876543,
    amount: 4200,
    currentStatus: 'Active',
  },
  {
    createdAt: '12-Feb-2023',
    expiresAt: '17-Mar-2023',
    stripeId: 4567890,
    amount: 5500,
    currentStatus: 'Pending',
  },
  {
    createdAt: '08-Apr-2023',
    expiresAt: '08-May-2023',
    stripeId: 1357924,
    amount: 6700,
    currentStatus: 'Expired',
  },
  {
    createdAt: '22-May-2023',
    expiresAt: '22-Jun-2023',
    stripeId: 2468135,
    amount: 3200,
    currentStatus: 'Active',
  },
  {
    createdAt: '18-Jul-2023',
    expiresAt: '18-Aug-2023',
    stripeId: 7890123,
    amount: 8800,
    currentStatus: 'Pending',
  },
  {
    createdAt: '03-Sep-2023',
    expiresAt: '03-Oct-2023',
    stripeId: 1597532,
    amount: 4900,
    currentStatus: 'Expired',
  },
  {
    createdAt: '11-Oct-2023',
    expiresAt: '11-Nov-2023',
    stripeId: 3571594,
    amount: 6100,
    currentStatus: 'Active',
  },
  {
    createdAt: '27-Nov-2023',
    expiresAt: '27-Dec-2023',
    stripeId: 8024671,
    amount: 7300,
    currentStatus: 'Pending',
  },
];

export const reviews = [
  {
    username: 'John',
    rating: 5,
    content: 'Excellent product! Highly recommended.',
    images: ['image1.jpg', 'image2.jpg'],
    createdAt: '01-Jan-2023',
  },
  {
    username: 'Alice',
    rating: 4,
    content: 'Impressed with the quality.',
    images: ['image3.jpg'],
    createdAt: '05-Jan-2023',
  },
  {
    username: 'Bob',
    rating: 1,
    content: 'Not bad, but could be better.',
    images: [],
    createdAt: '10-Jan-2023',
  },
  {
    username: 'Eva',
    rating: 5,
    content: 'Absolutely love it!',
    images: ['image4.jpg', 'image5.jpg'],
    createdAt: '15-Jan-2023',
  },
  {
    username: 'Chris',
    rating: 2,
    content: 'Disappointing experience.',
    images: [],
    createdAt: '20-Jan-2023',
  },
  {
    username: 'Sophie',
    rating: 4,
    content: 'Good value for money.',
    images: ['image6.jpg'],
    createdAt: '25-Jan-2023',
  },
  {
    username: 'Grace',
    rating: 2,
    content: 'Not satisfied with the purchase.',
    images: [],
    createdAt: '15-Feb-2023',
  },
  {
    username: 'Henry',
    rating: 3,
    content: 'Decent product, but needs improvement.',
    images: ['image10.jpg'],
    createdAt: '20-Feb-2023',
  },
  {
    username: 'Ivy',
    rating: 5,
    content: 'Amazing quality and fast delivery!',
    images: ['image11.jpg', 'image12.jpg'],
    createdAt: '25-Feb-2023',
  },
  {
    username: 'Jack',
    rating: 4,
    content: 'Happy with my purchase.',
    images: ['image13.jpg'],
    createdAt: '01-Mar-2023',
  },
  {
    username: 'Katie',
    rating: 3,
    content: 'Just okay, nothing extraordinary.',
    images: [],
    createdAt: '05-Mar-2023',
  },
  {
    username: 'Liam',
    rating: 5,
    content: 'Best product I have ever bought!',
    images: ['image14.jpg', 'image15.jpg'],
    createdAt: '10-Mar-2023',
  },
  {
    username: 'Mia',
    rating: 2,
    content: 'Poor quality, not worth the price.',
    images: [],
    createdAt: '15-Mar-2023',
  },
  {
    username: 'Noah',
    rating: 4,
    content: 'Satisfied with the performance.',
    images: ['image16.jpg'],
    createdAt: '20-Mar-2023',
  },
  {
    username: 'Olivia',
    rating: 3,
    content: 'Could be better for the price.',
    images: [],
    createdAt: '25-Mar-2023',
  },
  {
    username: 'Paul',
    rating: 5,
    content: 'Excellent customer service!',
    images: ['image17.jpg', 'image18.jpg'],
    createdAt: '01-Apr-2023',
  },
  {
    username: 'Quinn',
    rating: 4,
    content: 'Good product, fast shipping.',
    images: ['image19.jpg'],
    createdAt: '05-Apr-2023',
  },
  {
    username: 'Ryan',
    rating: 3,
    content: 'Average experience, nothing outstanding.',
    images: [],
    createdAt: '10-Apr-2023',
  },
  {
    username: 'Sofia',
    rating: 5,
    content: 'Impressive quality and design!',
    images: ['image20.jpg', 'image21.jpg'],
    createdAt: '15-Apr-2023',
  },
  {
    username: 'Tyler',
    rating: 2,
    content: 'Not happy with the product.',
    images: [],
    createdAt: '20-Apr-2023',
  },
  {
    username: 'Uma',
    rating: 4,
    content: 'Value for money, good deal!',
    images: ['image22.jpg'],
    createdAt: '25-Apr-2023',
  },
  {
    username: 'Victor',
    rating: 3,
    content: 'Average quality, but does the job.',
    images: [],
    createdAt: '01-May-2023',
  },
  {
    username: 'Wendy',
    rating: 5,
    content: 'Absolutely fantastic!',
    images: ['image23.jpg', 'image24.jpg'],
    createdAt: '05-May-2023',
  },
  {
    username: 'Xander',
    rating: 4,
    content: 'Satisfied with the purchase.',
    images: ['image25.jpg'],
    createdAt: '10-May-2023',
  },
  {
    username: 'Yara',
    rating: 2,
    content: 'Not what I expected, disappointed.',
    images: [],
    createdAt: '15-May-2023',
  },
  {
    username: 'Zane',
    rating: 3,
    content: 'Average product, nothing special.',
    images: ['image26.jpg'],
    createdAt: '20-May-2023',
  },
  {
    username: 'Ava',
    rating: 5,
    content: 'Highly recommend!',
    images: ['image27.jpg', 'image28.jpg'],
    createdAt: '25-May-2023',
  },
  {
    username: 'Ben',
    rating: 4,
    content: 'Good value for money.',
    images: ['image29.jpg'],
    createdAt: '01-Jun-2023',
  },
  {
    username: 'Cara',
    rating: 3,
    content: 'Not bad, but not great either.',
    images: [],
    createdAt: '05-Jun-2023',
  },
  {
    username: 'David',
    rating: 5,
    content: 'Outstanding product!',
    images: ['image30.jpg', 'image31.jpg'],
    createdAt: '10-Jun-2023',
  },
  {
    username: 'Felix',
    rating: 2,
    content: 'Disappointed with the quality.',
    images: [],
    createdAt: '20-Jun-2023',
  },
  {
    username: 'Gina',
    rating: 3,
    content: 'Average experience, nothing extraordinary.',
    images: ['image33.jpg'],
    createdAt: '25-Jun-2023',
  },
  {
    username: 'Hank',
    rating: 5,
    content: 'Top-notch quality!',
    images: ['image34.jpg', 'image35.jpg'],
    createdAt: '01-Jul-2023',
  },
  {
    username: 'Isla',
    rating: 4,
    content: 'Good product, meets expectations.',
    images: ['image36.jpg'],
    createdAt: '05-Jul-2023',
  },
  {
    username: 'Jake',
    rating: 3,
    content: 'Could be better for the price.',
    images: [],
    createdAt: '10-Jul-2023',
  },
  {
    username: 'Kara',
    rating: 5,
    content: 'Fantastic service and product!',
    images: ['image37.jpg', 'image38.jpg'],
    createdAt: '15-Jul-2023',
  },
  {
    username: 'Liam',
    rating: 2,
    content: 'Not satisfied with the purchase.',
    images: [],
    createdAt: '20-Jul-2023',
  },
  {
    username: 'Mila',
    rating: 4,
    content: 'Impressed with the durability.',
    images: ['image39.jpg'],
    createdAt: '25-Jul-2023',
  },
  {
    username: 'Nolan',
    rating: 3,
    content: 'Average product, nothing special.',
    images: [],
    createdAt: '01-Aug-2023',
  },
  {
    username: 'Olivia',
    rating: 5,
    content: 'Amazing quality and design!',
    images: ['image40.jpg', 'image41.jpg'],
    createdAt: '05-Aug-2023',
  },
  {
    username: 'Pete',
    rating: 4,
    content: 'Well worth the money.',
    images: ['image42.jpg'],
    createdAt: '10-Aug-2023',
  },
  {
    username: 'Quincy',
    rating: 2,
    content: 'Not living up to expectations.',
    images: [],
    createdAt: '15-Aug-2023',
  },
  {
    username: 'Rachel',
    rating: 3,
    content: 'Decent product, but needs improvement.',
    images: ['image43.jpg'],
    createdAt: '20-Aug-2023',
  },
  {
    username: 'Sam',
    rating: 5,
    content: 'Exceptional quality and service!',
    images: ['image44.jpg', 'image45.jpg'],
    createdAt: '25-Aug-2023',
  },
  {
    username: 'Tessa',
    rating: 4,
    content: 'Good value for the price.',
    images: ['image46.jpg'],
    createdAt: '01-Sep-2023',
  },
  {
    username: 'Tessa',
    rating: 4,
    content: 'Good value for the price.',
    images: ['image46.jpg'],
    createdAt: '02-Sep-2023',
  },
  {
    username: 'Tessa',
    rating: 4,
    content: 'Good value for the price.',
    images: ['image46.jpg'],
    createdAt: '02-Sep-2023',
  },
  {
    username: 'Ulysses',
    rating: 3,
    content: 'Average experience, nothing outstanding.',
    images: [],
    createdAt: '05-Sep-2023',
  },
  {
    username: 'Victoria',
    rating: 5,
    content: 'Absolutely satisfied!',
    images: ['image47.jpg', 'image48.jpg'],
    createdAt: '10-Sep-2023',
  },
  {
    username: 'Walter',
    rating: 4,
    content: 'Happy with the purchase.',
    images: ['image49.jpg'],
    createdAt: '15-Sep-2023',
  },
  {
    username: 'Xena',
    rating: 1,
    content: 'Not as expected, disappointed.',
    images: [],
    createdAt: '20-Sep-2023',
  },
  {
    username: 'Yuki',
    rating: 3,
    content: 'Average product, nothing special.',
    images: ['image50.jpg'],
    createdAt: '25-Sep-2023',
  },
];

export const logs = [
  {
    name: 'The Pizza Hut',
    requestType: 'Modify',
    status: 'approved',
    remarks: 'Restaurant was relisted',
  },
  {
    name: 'Kababjees',
    requestType: 'Listing',
    status: 'rejected',
    remarks: 'Tax ID incorrect',
  },
];

export const restaurants = [
  {
    name: 'The Pizza Hut',
    categories: ['Mexican', 'Italian', 'Chinese', 'Fast Food', 'Sea Food'],
    menu: [
      {
        Appetizer: ['Salad', 'Cheese Sticks'],
        'Main Course': ['Fried Broast', 'Chicken Burger'],
        Beverages: ['Pepsi', 'Bounty Shake', 'Lemon Masti'],
      },
    ],
  },
  {
    name: 'Sizzling Wok',
    categories: ['Chinese'],
    menu: [
      {
        Appetizer: ['Spring Rolls', 'Wontons'],
        'Main Course': ['Kung Pao Chicken', 'Pad Thai'],
        Beverages: ['Green Tea', 'Lychee Punch', 'Mango Lassi'],
      },
    ],
  },
  {
    name: 'Mamma Mia Pizzeria',
    categories: ['Italian', 'Fast Food'],
    menu: [
      {
        Appetizer: ['Bruschetta', 'Caprese Salad'],
        'Main Course': ['Margherita Pizza', 'Pasta Carbonara'],
        Beverages: ['Red Wine', 'Limoncello'],
      },
    ],
  },
  {
    name: 'Dragon Delights',
    categories: ['Chinese', 'Fast Food'],
    menu: [
      {
        Appetizer: ['Edamame', 'Gyoza'],
        'Main Course': ['Teriyaki Chicken', 'Sushi Platter'],
        Beverages: ['Green Tea', 'Sake'],
      },
    ],
  },
  {
    name: 'Speedy Bites',
    categories: ['Fast Food', 'Italian'],
    menu: [
      {
        Appetizer: ['Mozzarella Sticks', 'Onion Rings'],
        'Main Course': ['Double Cheeseburger', 'Chicken Nuggets'],
        Beverages: ['Cola', 'Iced Tea'],
      },
    ],
  },
  {
    name: 'Ocean Feast',
    categories: ['Seafood'],
    menu: [
      {
        Appetizer: ['Calamari', 'Shrimp Cocktail'],
        'Main Course': ['Grilled Salmon', 'Seafood Paella'],
        Beverages: ['White Wine', 'Sangria'],
      },
    ],
  },
  {
    name: 'Taste of Asia',
    categories: ['Chinese'],
    menu: [
      {
        Appetizer: ['Samosa', 'Egg Rolls'],
        'Main Course': ['Chicken Tikka Masala', 'Sushi Roll Combo'],
        Beverages: ['Mango Lassi', 'Masala Chai'],
      },
    ],
  },
  {
    name: 'Green Garden Cafe',
    categories: ['Mexican'],
    menu: [
      {
        Appetizer: ['Hummus Platter', 'Vegetable Spring Rolls'],
        'Main Course': ['Quinoa Bowl', 'Stuffed Bell Peppers'],
        Beverages: ['Detox Smoothie', 'Matcha Latte'],
      },
    ],
  },
  {
    name: 'Flavors of Mexico',
    categories: ['Mexican'],
    menu: [
      {
        Appetizer: ['Guacamole', 'Queso Fundido'],
        'Main Course': ['Tacos Al Pastor', 'Enchiladas'],
        Beverages: ['Margarita', 'Horchata'],
      },
    ],
  },
  {
    name: 'Spice Fusion',
    categories: ['Italian'],
    menu: [
      {
        Appetizer: ['Samosa Chaat', 'Falafel'],
        'Main Course': ['Butter Chicken', 'Chicken Shawarma'],
        Beverages: ['Mango Lassi', 'Cardamom Chai'],
      },
    ],
  },
  {
    name: 'Burger Haven',
    categories: ['Fast Food', 'American'],
    menu: [
      {
        Appetizer: ['Cheese Fries', 'Onion Rings'],
        'Main Course': ['Classic Burger', 'BBQ Bacon Burger'],
        Beverages: ['Root Beer', 'Chocolate Shake'],
      },
    ],
  },
  {
    name: 'Noodle Nirvana',
    categories: ['Chinese'],
    menu: [
      {
        Appetizer: ['Potstickers', 'Tom Yum Soup'],
        'Main Course': ['Chow Mein', 'Udon Noodles'],
        Beverages: ['Green Tea', 'Thai Iced Tea'],
      },
    ],
  },
  {
    name: 'Mediterranean Delights',
    categories: ['Mexican', 'Italian'],
    menu: [
      {
        Appetizer: ['Feta Bruschetta', 'Greek Salad'],
        'Main Course': ['Moussaka', 'Falafel Wrap'],
        Beverages: ['Ouzo', 'Pomegranate Juice'],
      },
    ],
  },
  {
    name: 'Tandoori Nights',
    categories: ['Italian'],
    menu: [
      {
        Appetizer: ['Chicken Tikka', 'Paneer Tikka'],
        'Main Course': ['Chicken Biryani', 'Saag Paneer'],
        Beverages: ['Lassi', 'Mango Lassi'],
      },
    ],
  },
  {
    name: 'Sushi Savor',
    categories: ['Italian'],
    menu: [
      {
        Appetizer: ['Edamame', 'Miso Soup'],
        'Main Course': ['Sashimi Platter', 'Dragon Roll'],
        Beverages: ['Green Tea', 'Sake'],
      },
    ],
  },
  {
    name: 'Tasty Tandoor',
    categories: ['Italian'],
    menu: [
      {
        Appetizer: ['Vegetable Samosa', 'Chicken Seekh Kebab'],
        'Main Course': ['Chicken Curry', 'Paneer Butter Masala'],
        Beverages: ['Mango Lassi', 'Masala Chai'],
      },
    ],
  },
  {
    name: 'Pasta Paradise',
    categories: ['Italian'],
    menu: [
      {
        Appetizer: ['Garlic Bread', 'Caprese Salad'],
        'Main Course': ['Spaghetti Bolognese', 'Chicken Alfredo'],
        Beverages: ['Red Wine', 'Sparkling Water'],
      },
    ],
  },
  {
    name: 'Sizzling Szechuan',
    categories: ['Chinese'],
    menu: [
      {
        Appetizer: ['Egg Rolls', 'Hot and Sour Soup'],
        'Main Course': ['Kung Pao Chicken', 'Beef with Broccoli'],
        Beverages: ['Jasmine Tea', 'Lychee Lemonade'],
      },
    ],
  },
  {
    name: 'Veggie Vibes',
    categories: ['Sea Food'],
    menu: [
      {
        Appetizer: ['Brussels Sprouts Chips', 'Sweet Potato Fries'],
        'Main Course': ['Quinoa Salad', 'Stuffed Portobello Mushrooms'],
        Beverages: ['Green Smoothie', 'Coconut Water'],
      },
    ],
  },
  {
    name: 'Crispy Crunch',
    categories: ['Fast Food', 'Sea Food'],
    menu: [
      {
        Appetizer: ['Chicken Wings', 'Mozzarella Bites'],
        'Main Course': ['Crispy Chicken Sandwich', 'BBQ Bacon Fries'],
        Beverages: ['Cola', 'Root Beer Float'],
      },
    ],
  },
];
